### PR TITLE
barycentric vpolytope sampler

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/wernerpe/drake/14)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@wernerpe for feature review

> *[Reviewable](https://reviewable.io/reviews/wernerpe/drake/14#-:-O9KmCIk5a8AXwbUswrR:b96396b)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @wernerpe)

**Review by wernerpe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wernerpe/drake/14)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[`planning/iris/barycentric_vpolytope_sampler.h` line 19 at r1](https://reviewable.io/reviews/wernerpe/drake/14#-O9Vg6GPBEgABMlSRGZz:-O9Vg6GPBEgABMlSRG_-:bwbdobf) ([raw file](https://github.com/wernerpe/drake/blob/29fc1d1b5d299acf60ae58ed62b792c53ddefc38/planning/iris/barycentric_vpolytope_sampler.h#L19)):*
> ```objc
>  * If sampling_always_returns_vertices is true and the requested number of
>  * points is larger than the number of vertices, the first |vertices| samples
>  * will be the vertices of the domain.
> ```

Maybe we should already drop the reference https://www.cs.cmu.edu/~nasmith/papers/smith+tromble.tr04.pdf here to explain why we are using the generalized bc coords? WDYT?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wernerpe/drake/14)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @wernerpe)

___
*[`planning/iris/barycentric_vpolytope_sampler.h` line 19 at r1](https://reviewable.io/reviews/wernerpe/drake/14#-O9Vg6GPBEgABMlSRGZz:-O9VkLKzBiNy2PIYc1CA:bvzelpc) ([raw file](https://github.com/wernerpe/drake/blob/29fc1d1b5d299acf60ae58ed62b792c53ddefc38/planning/iris/barycentric_vpolytope_sampler.h#L19)):*
<details><summary><i>Previously, wernerpe (Peter Werner) wrote…</i></summary><blockquote>

Maybe we should already drop the reference https://www.cs.cmu.edu/~nasmith/papers/smith+tromble.tr04.pdf here to explain why we are using the generalized bc coords? WDYT?
</blockquote></details>

Good call.

I also want to add the ability to weight vertices. WDYT?

**Review by wernerpe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wernerpe/drake/14)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[`planning/iris/barycentric_vpolytope_sampler.h` line 19 at r1](https://reviewable.io/reviews/wernerpe/drake/14#-O9Vg6GPBEgABMlSRGZz:-O9Vn7Su6CPZaRrTTB_3:bgz0no8) ([raw file](https://github.com/wernerpe/drake/blob/29fc1d1b5d299acf60ae58ed62b792c53ddefc38/planning/iris/barycentric_vpolytope_sampler.h#L19)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Good call.

I also want to add the ability to weight vertices. WDYT?
</blockquote></details>

What is the scenario where we would want to do that? I think if there is a clear scenario it def makes sense and we should add it in.

**Review by wernerpe — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/wernerpe/drake/14#-:-O9uUCE1DKnZfWef-KZY:bnfp4nl)* status: 0 of 15 files reviewed, all discussions resolved

**Pull request merged**
