### PR TITLE
A more flexible implementation of IrisFromCliqueCover

### PR DESCRIPTION
**Pull request by AlexandreAmice**
See IrisFromCliqueCoverTemplate and the tests in both planning/iris and bindings/pydrake/planning for examples.

- - -
This change is [Reviewable](https://reviewable.io/reviews/wernerpe/drake/9)

### CODE REVIEW

**Review by wernerpe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wernerpe/drake/9)* status: 0 of 46 files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[`planning/iris/iris_from_clique_cover_template.cc` line 172 at r1](https://reviewable.io/reviews/wernerpe/drake/9#-O74nAaS6cozk1_P-xJg:-O74nAaS6cozk1_P-xJh:bh8mm94) ([raw file](https://github.com/wernerpe/drake/blob/430b62e5cb20fbb8d1626d4b4aeab006f8449b74/planning/iris/iris_from_clique_cover_template.cc#L172)):*
> ```cpp
>   int ctr = 0;
>   while (ctr < options.iteration_limit &&
>          !internal::IsSufficientlyCovered(
> ```

We need to make sure to decay the delta correctly here. We want delta = 1 - confidence error probability over the entire procedure. To do this correctly we need to decay delta over the individual visibility rounds (delta_k = 6delta/(pi^2*k^2)) , see https://groups.csail.mit.edu/robotics-center/public_papers/Werner24.pdf .

**Review by wernerpe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wernerpe/drake/9)* status: 0 of 47 files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[`planning/iris/iris_from_clique_cover_template.cc` line 172 at r1](https://reviewable.io/reviews/wernerpe/drake/9#-O74nAaS6cozk1_P-xJg:-O7AE-Qd0q-bx_m0qk1Z:b-1bltuc) ([raw file](https://github.com/wernerpe/drake/blob/430b62e5cb20fbb8d1626d4b4aeab006f8449b74/planning/iris/iris_from_clique_cover_template.cc#L172)):*
<details><summary><i>Previously, wernerpe (Peter Werner) wrote…</i></summary><blockquote>

We need to make sure to decay the delta correctly here. We want delta = 1 - confidence error probability over the entire procedure. To do this correctly we need to decay delta over the individual visibility rounds (delta_k = 6delta/(pi^2*k^2)) , see https://groups.csail.mit.edu/robotics-center/public_papers/Werner24.pdf .
</blockquote></details>

Wait something seems quite off here. You need to scale the confidence not the coverage threshold. The delta not the epsilon. It should look something like epsilon = 1- coverage threshold, and delta_k = 6delta/(pi^2\*k^2))

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wernerpe/drake/9)* status: 0 of 48 files reviewed, 1 unresolved discussion (waiting on @wernerpe)

___
*[`planning/iris/iris_from_clique_cover_template.cc` line 172 at r1](https://reviewable.io/reviews/wernerpe/drake/9#-O74nAaS6cozk1_P-xJg:-O7jskrb9NHf64lv6Zkk:b-8zy1d7) ([raw file](https://github.com/wernerpe/drake/blob/430b62e5cb20fbb8d1626d4b4aeab006f8449b74/planning/iris/iris_from_clique_cover_template.cc#L172)):*
<details><summary><i>Previously, wernerpe (Peter Werner) wrote…</i></summary><blockquote>

Wait something seems quite off here. You need to scale the confidence not the coverage threshold. The delta not the epsilon. It should look something like epsilon = 1- coverage threshold, and delta_k = 6delta/(pi^2\*k^2))
</blockquote></details>

Whoops 😅. Good catch.

**Review by wernerpe — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/wernerpe/drake/9#-:-O9GCFhkCknC8kgwDT9c:bg7igkv)* status: 0 of 48 files reviewed, 1 unresolved discussion

**Pull request merged**
